import os
from PIL import Image
from flask import url_for, current_app
from flask_mail import Message
from flaskblog import mail


def save_picture(form_picture):
    f_name, f_ext = os.path.splitext(form_picture.filename)
    picture_path = os.path.join(current_app.root_path, 'static/profile_pics', f_name + f_ext)
    output_size = (125, 125)
    i = Image.open(form_picture)
    i.thumbnail(output_size)
    i.save(picture_path)
    return f_name + f_ext


def send_reset_email(user):
    token = user.get_reset_token()
    msg = Message('Password Reset Request',
                  sender='no-reply@testingdemo.com', recipients=[user.email])
    msg.body = '''To reset password, click on the link given below:
{}
Please ignore, if not generated by you.
'''.format(url_for('users.reset_token', token=token, _external=True))
    # print ("\n\n", "data:", msg.body, "\n\n", file=sys.stdout)
    mail.send(msg)
